pipeline {
    agent any
    environment {
        POM_VERSION = ""
    }
    stages {
        stage('Build') {
            steps{
                sh 'graddle build'
            }
            post {
                success {
                    echo 'perfect'
                }
            }
        }
    }
}