pipeline {
    agent any
    tools {
        maven 'maven 3.8.6'
        jdk 'jdk9'
    }
    stages {
        stage('Build') {
            steps{
                sh 'mvn -Dmaven.test.failure.ignore=true install'
            }
            post {
                success {
                    echo 'perfect'
                }
            }
        }
    }
}